### ISSUE TITLE
Multiple BA.2.86*+S:T95X  9 ongoing branchs as 2/28

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1135]
Besides JQ.1, there seems to be multiple BA.2.86* with S:T95I

Query for all seqs: A7842, C8293T, G8393A, Spike_T95 (554 seqs)
```[tasklist]
### Tasks
- [x] [JQ.1]():Query: C1960T,T12775C,C21846T,A29510C Already designated (303 seqs)
- [x] [Branch 1,BA.2.86.1+S:T95I, Pango #2449(Dead)](https://github.com/cov-lineages/pango-designation/issues/2449):Query: C21846T,A6183G,C12815T,-11750,-3565,-A2127G (31 seqs, 02/10)
- [x] [Branch 2, JN.1+S:T95I, Designated JN.1.10](https://github.com/cov-lineages/pango-designation/issues/2450):Query: -11747,-C1060T,C21846T,T3565,A6183G,-26894,-6813,-C774T (45 seqs)
- [ ] [Branch 3,JN.1.1+S:T95I](): Query: -C24130T,-9142, C11747T, C21846T, C1762A,-del21768, -C1063T,-22599,-8884 14 seqs Netherlands, Spain, Canada, France, UK, India,Switzerland Some of the seqs on this branch are put to JN.1.3 due to additional Orf8:Q18*.
- [x] [Branch 4, JN.2+Orf1b:I1725V+Orf1a:Y3765C+S:T95I,A475V](): Query: A2127G, C21846T, A18640G, 10 seqs, Sweden ] Dead
- [x] [Branch 5, JN.1.1+C9142T+S:T95,DeadI](): Query: C24130T, C9142T,C11747T, C21846T, C1762A 8 seqs, France, Belgium,Luxembourg, 02/10
- [x] [Branch 6, BA.2.86.1+S:T95S,Dead](): Query: T14022C,C21846G, 5 seqs, Germany
- [ ] Branch 7,XDK+S:T95I,N:H145Q: Query: C5314T, C21846T, C28708G, 5 seqs, France
- [x] Branch 8, JN.1.1+S:R346T+Orf1a:K1305N,S:T95I, Dead: Query: C11747T,C21846T,G22599C,C897A, 5 seqs, Spain, France
- [x] Branch 9, JN.1+C26894T+C25680T+S:T95I, Dead: Query: C26894T,C25680T,C21846T,T3565C 3 seqs, USA
- [ ] Branch 10, JN.1+C21646T+S:T95I, Query: C21646T,C21846T,C18894T 4 seqs, USA
- [x] Branch 11, JN.2.2+G13240A+S:T95I, Dead, Query: G13240A,C21846T,A2127G, 3 seqs, Germany
- [ ] Branch 12, JN.1.4+S:T95I, Query: C774T, -18453, C21846T, T3565C, 6 seqs, USA,UK,Germany,France
- [ ] Branch 13, JN.1+A9085G,T24046C+S:T95I, Query: A9085G,T24046C,C21846T, 3 seqs, Spain, UK
```

Doublets:
1. BA.2.86.1+Orf1a:S2193F,L3829F, Orf1b:T1743I,S:T95I: Query: C21846T,A6183G,C12815T,C11750T, UK dead
2. JN.1+Orf1a:T2183I+Orf1b:P1287S,S:T95I,S691P. Query: C21846T,C17326T,T23633C, UK (1 not on GISAID) dead
3. JN.1.4+Orf1b:M187A+Orf1a:I2490T,A1679V,A4257V, S:T95I,Orf8:I9T. Query: C774T, C21846T, A14026G, Sweden dead
4. JN.1.1+T27785C+S:S12F,S:T95I Query: C9142T,T27785C, C21846T, Switzerland Dead
5. #1089 branch 3+S:T95I : Query: C22599C,C11747T,C21846T, C1762A, France
6. JN.1+Orf1b:G1568S,S:T95I: Query: G18169A,C21846T,T3565C, UK Dead

Singlets:
1. JN.1.1+Orf1a:T2800N+Orf1a:H2092Y+S:T95I. Query: C11747T, C21846T, C1063T, Canada dead
7. JN.1.19(Orf8:I71V)+N:P46S, S:T95I, Query: C1060T,C21846T,A6183G,T3565C, Denmark dead
8. JN.2.2+S:T95I, Query: T1030C,C21846T,A2127G, Germany dead
9. JN.2+G28378T+S:T95I, Query: C21846T,G28378T,A2127G,A6183G, China Dead
10. JN.1+C26894T+C25680T+S:T95I, Query: C26894T,T3565C,C21846T, USA, 2 seqs 
11. JN.1.4+S:T95N, Query:C774T,C21846A, USA
12. #1091+S:T95S, Query:  C23277T,C21846G, UK dead
13. BA.2.86+S:T95S,Orf3a:A110S, Query: C21846G, G25720T,C11008T, South Africa dead

usher for Branch 1 :
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_1a2be_95c9c0.json?label=id:node_4485736)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/93f0accb-9e7f-40e8-9865-f1aa34fb7a69)

usher for Branch 2:
[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_1a2be_95c9d0.json?label=id:node_4484735)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/258f4ccc-5c67-4d62-86d3-fc3c6f8fbd44)

**Comment by FedeGueli** [comment]
Branch 3 at 7

**Comment by FedeGueli** [comment]
B1 > 18
B2 > 11

B3 and B4 appear to be slow.

**Comment by aviczhl2** [comment]
A previous doublet is now 4 seqs and becomes B5

**Comment by aviczhl2** [comment]
1/11: 
Add singlet 4,5 Doublet 2. 
Branch 1 becomes 23 and Branch 2 becomes 21.

**Comment by FedeGueli** [comment]
Please propose branch 1 and branch 2.

**Comment by FedeGueli** [comment]
Branch 2 Designated JN.1.10 via https://github.com/cov-lineages/pango-designation/commit/65d1e22e9db0059ed314889b75372967c32040a8

**Comment by aviczhl2** [comment]
@AngieHinrichs, it seems that JQ.1 with 487 missing coverage are all categorized into BA.2.86.3+G487A+S:T95I sub-branch despite no seq actually have G487A, better fix it.

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_2093a_516210.json?gt=nuc.487A&label=id:node_6871938)

**Comment by aviczhl2** [comment]
1-15, Add some S:T95S and S:T95N branches (most of them already died off though)

**Comment by AngieHinrichs** [comment]
> @AngieHinrichs, it seems that JQ.1 with 487 missing coverage are all categorized into BA.2.86.3+G487A+S:T95I sub-branch despite no seq actually have G487A, better fix it.
Thanks -- I think that is fixed as of the 2024-01-17 tree.

**Comment by aviczhl2** [comment]
2/4: Add branch 7 and branch 8.

**Comment by FedeGueli** [comment]
It seems just branch 3 has some chances to emerge. lets keep this open for a while more.

**Comment by aviczhl2** [comment]
2/15: Add branch 9 and 10

**Comment by aviczhl2** [comment]
2/28, Add branch 11-13

**Comment by aviczhl2** [comment]
Seems that all branches are not growing.

**Comment by FedeGueli** [comment]
Thanks ! agree with u
