### ISSUE TITLE
Multiple branches of JN.1*+S:S221L   3 branches as of 2/18

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1318]
General query: C18894T,T3565C, Spike_S221  (179 seqs)

```[tasklist]
### Tasks
- [ ] Branch 1: JN.1+S:S221L: Query: T3565C,C18894T,C22224T,-C1762A,-C774T,-8578,-G3875T,-C1060T,-C7594T,-13663,-25429,-25327, -9935,-26639,-18471,-8094,-G5305A,-17562,-26599,-18674,-27654,-7113,-19011,-13019,-25249,-C1314T,-G2782T,-T4885C,-C4048T 33 seq, USA, India,Sweden,Denmark, France,UK,Canada,Spain,Malaysia, Brazil,China, Argentina, Norway, Russia,Singapore, South Korea
- [ ] Branch 2: JN.1+C7594T+C8074T+S:S221L: Query: C7594T, C18894T,C22224T, 101 seqs, Canada, Germany, France, USA
- [ ] Branch 3: JN.1.4+G5008T,T24052C,S:S221L:Query: G5008T,T24052C,C22224T, 14 seqs, USA,UK,Netherlands
```
Also a lot of singlets and doublets. Too many(>10). Will only update them when they become >2.

**Comment by FedeGueli** [comment]
221L was alos one of the first of homoplasic XBB.1.5 but without a lot of success, same for HV.1 where it got designated as HV.1.7 , my feeling is that it is not advantageous in pop spread , but maybe yes intrahost so we see a lot of branches with it but few or none getting fixated then. Lets see if this time is different with BA.2.86 backbone

**Comment by aviczhl2** [comment]
1/26: Branch 2 reaches 51.

**Comment by aviczhl2** [comment]
2/6: Add branch 3

**Comment by FedeGueli** [comment]
21-81-6 now the three branches

**Comment by FedeGueli** [comment]
Again it seems not advantageous. but it keeps emerging .

**Comment by aviczhl2** [comment]
Branch 1 reaches 50 and Branch 2 reaches 101.

**Comment by FedeGueli** [comment]
Please propose Branch 1 , although with less sequences it seems more widely spread and with some very recent samples too

**Comment by aviczhl2** [comment]
> Please propose Branch 1 , although with less sequences it seems more widely spread and with some very recent samples too

I check this lineage and find a dozen new separate emergences of S:S221L. It's really hard to get a correct query.

**Comment by aviczhl2** [comment]
I don't think I can track branch 1 with a proper query. Close this.

**Comment by FedeGueli** [comment]
Branch 2 up to 116 but it doesnt seem able to do any difference
