### ISSUE TITLE
Multiple JN.1* lineages with S:F32del

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1768]
It seems that like S:S31del, there is also lots of S:F32del branches emerging.

As it is basically having similar function as S:S31del, DeFLiRT/DeFLuQE still works. 

```[tasklist]
### Tasks
- [x] **DeFLiRT Branch 1, designated KP.2.6** Query:  del21656,T21752A
- [ ] **DeFLiRT Branch 2**, KP.2+T22795G+T24637G+S:F32del, Proposed in https://github.com/cov-lineages/pango-designation/issues/2715
- [x] **DeFLiRT Branch 3,DEAD**, KP.2+T22795G+Orf1a:A1485V, Orf1b:T1363I, S:H445Y, S:F32del, Query: del21656_21658, G22895T,C17555T, 8 seqs, USA, UK, France, Netherlands (likely dead)
- [ ] **DeFLiRT Branch 4**, KP.2+Orf1a:P1803L, S:K558N, S:F32del, Proposed in https://github.com/cov-lineages/pango-designation/issues/2736
- [ ] Branch 5,, JN.1+Orf1a:A339V,S:F32del, Query: del21656_21658, C1281T,T25818C, 10 seqs, Ukraine, many with S:R346T
```

**Comment by FedeGueli** [comment]
Credit to @Sinickle that spotted it in KP.2.6

**Comment by FedeGueli** [comment]
Most of the samples are very recent soemthing to watch thks @aviczhl2 for opening this one.

**Comment by Mydtlwn** [comment]
To distinguish from S:S31del, I suggest adjusting the combined name of S:F32del to De2FLiRT or De2FLuQE. If both mutations are present, they can be called 2DeFLiRT and 2DeFLuQE. Those with S:F59L can also be referred to as 2FLiRT and 2FLuQE.

**Comment by aviczhl2** [comment]
> To distinguish from S:S31del, I suggest adjusting the combined name of S:F32del to De2FLiRT or De2FLuQE. If both mutations are present, they can be called 2DeFLiRT and 2DeFLuQE. Those with S:F59L can also be referred to as 2FLiRT and 2FLuQE.

It is unlikely for both to present simutaneously, as it will destroy the N Glycan and may not grow.

**Comment by Mydtlwn** [comment]
You're absolutely right, but this is just one possible scenario. Actually, I don't favor the simultaneous occurrence of both mutations either.

**Comment by rchorowski** [comment]
When did you add the tag "N Glycan" to the repo? I mean when did you start to tag the lineages with this tag?

**Comment by aviczhl2** [comment]
Branch 2 becomes 21, branch 4 becomes 17

**Comment by FedeGueli** [comment]
> Branch 2 becomes 21, branch 4 becomes 17

Br.2 is 30% of recent samples collected (or related to) Ecuador. Please propose it , thx for tracking it.

**Comment by FedeGueli** [comment]
> When did you add the tag "N Glycan" to the repo? I mean when did you start to tag the lineages with this tag?

since it became relevant with DeFLIRT after DEFLiRT

**Comment by aviczhl2** [comment]
Branch 4 becomes 24. The other 2 seems dead.

**Comment by aviczhl2** [comment]
Branch 5 becomes 10 and still circulating in Ukraine in July.

**Comment by aviczhl2** [comment]
And Branch 4 is 26 in 11 countries now.

**Comment by FedeGueli** [comment]
> And Branch 4 is 26 in 11 countries now.
 please propose it on Pango

**Comment by aviczhl2** [comment]
All significant branches are proposed. Close this one.

**Comment by FedeGueli** [comment]
Designated KP.2.25.2 via https://github.com/cov-lineages/pango-designation/commit/a3d38ca258578e6487aebe3e976302f258aeaeef

**Comment by FedeGueli** [comment]
Branch 2 designated KP.2.28 via https://github.com/cov-lineages/pango-designation/commit/fada0fe55abbb6b1dde5b4ec20a708ef17db2eca
