### ISSUE TITLE
Multiple LF.7+S:A475V branches (10 Branches  as of Jan 9)

### ISSUE THREAD

**Issue by xz-keg** [sars-cov-2-variants/lineage-proposals#2067]
```[tasklist]
### Tasks
- [x] Branch 1, LF.7+T20799C+S:A475V, **Designated LF.7.2.1**, GISAID query: T20799C,C22986T, 19 seqs, Singapore, USA, Turkey,Belgium, UK, Canada, Australia,Nigeria
- [x] Branch 2, LF.7.1+S:A475V, **Designated LF.7.1.2**, https://github.com/cov-lineages/pango-designation/issues/2805
- [x] Branch 3, LF.7+S:A475V, **Designated as parent of LF.7.9** GISAID query:T3565C,C8818T, T16600C,C22986T,-16017,-A4838G,-C2003T,-25624,-A1124G,-G8017T,-C17436T,-T20799C,-C6310T,-T847C,-C24444T,-C7688T,-C7051T,-G4504A,-G27415A,-C26607T,-G3939T 21 seqs, USA, Poland, Nigeria,Ireland, Denmark, Ghana (GBW), England, South Korea,Russia,Sweden,France,Qatar,Oman,Canada,
- [x] Branch 4 **Designated LF.7.3.1** Now proposed in https://github.com/cov-lineages/pango-designation/issues/2836 LF.7.3 (C17436T) > Orf1a:P2046L (C6402T) > S:A475V (C22986T) Query: C17436T,C6402T,C22986T, 23 seqs, Sweden, Hong Kong, Texas, NY, England, Qatar, France UK, Israel, Germany,Spain,Denmark
- [x] Branch 5 Dead LF.7 > C29119T > Orf1a:T224I (C936T), G8017T>ORF1a:T1542I (C4890T), ORF1a:P3767L (C11565T), S:H146H(C22000T), S:A475V (C22986T),G25012A,Query: C4890T, C11565T, G25012A, Seq : 1, Qatar
- [x] Branch 6 Dead LF.7.1.3 + 475V Seq.1 Netherlands LF.7.3.1 > ORF1a :L2062F, ORF3a:L41H(T25514A)> ORF1a:L590F (G2035T), T17688C, S:A475V (C22986T),ORF3a:G44R (G25522C) Query:G2035T, T17688C, G25522C , 2 Seq, Netherlands, Germany
- [x] Branch 7 Dead LF.7.1>> ORF1a:A2249V (C7011T) > G2659A, T3649C,G5539A,S:A475V (C22986T) Query: G2659A, T3649C,G5539A,t3565C Samples: 3 Qatar,Singapore
- [x] Branch 8 DEAD LF.7.1.3 >> S:A475V (C22986T) Query:C4068T,C22986T,T3565C,-G25699A,-C3828T,-C6449T,-T24910C Samples:16 Russia found by @Over-There-Is
- [x] Branch 9 DEAD LF.7.1.3 >> Orf1a:S1188L (C3828T)>T14619C,S:A475V (C22986T), C24130T, C25276T Query:C4068T,C3828T,T14619C Samples: 8 Japan, Russia found by @Over-There-Is
- [x] Branch 10 DEAD LF.7.1.3 >> Orf3a:A103T (G25699A)>> Orf1a:E37D (G376T),S:A475V (C22986T) Query: G25699A,G376T,T3565C Samples:2 Russia found by @Over-There-Is
- [x] Branch 11,DEAD LF.7.1+T191C+C19017T+S:A475V, Query: C6310T,C19017T,C22986T, 7 seqs, USA, Singapore, Saudi Arabia, Bahrain
- [x] Branch 12 DEAD LF.7.4 (S:T961M) >> G25494A > C832T, C16575T, C25276T > C1498T > S:A475V (C22986T, C29200T) Query: C22986T, C29200T,C1498T 1 Seqs NY
- [x] Branch 13 DEAD LF.7.7.1 [Orf1a:R1225I + S:T572I ]+ S:A475V tracked in https://github.com/cov-lineages/pango-designation/issues/2855 with C22986T,T6634A,C10594T
- [ ] Branch 14 LF.7.1.3>> S:S704L (C23673T) > T24910C, Orf3a:t24I (C25463T), C27800T > S:A475V (C22986T) Query: C25463T, C27800T ,C22986T Samples: 4 Russia
- [ ] Branch 15 LF.7.7.2 >> Orf1a:V337F (G1274T) > S:A475V (C22986T) Query: G1274T,C22986T,G3939T Samples: 12 Canada Cluster
- [ ] Branch 16 LF.7.7.1 > C10594T > S:A475V(C22986T) Query:-T6634A,-C8407T,C10594T,C22986T,G3939T Samples:8 Ecuador, Peru', Chile, Arizona, Rhode Island, Italy
```

<Details>
<Summary>
Original proposal:
</Summary>
LF.7+T20799C+C22986T(S:A475V)

GISAID query: T20799C,C22986T
No. of seqs: 3(USA 2(1 from Belgium), Canada 1)

First: EPI_ISL_19348783, USA-TX, 2024-7-29
Latest: EPI_ISL_19427318, USA from Belgium, 2024-9-9

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice18_genome_test_59505_da8440.json?label=id:node_5586103)
![image](https://github.com/user-attachments/assets/17d7c9a5-f290-4fc0-86f2-1c74e135f6d0)
</Details>

**Comment by HynnSpylor** [comment]
Ah I just mentioned the branch and meant to propose it.
Actually it is at least 4 seqs, and one more in Sierra Leone (EPI_ISL_19421077). Another LF.7+S:A475V seq in MD, US is EPI_19420046 without T20799C.

**Comment by aviczhl2** [comment]
> Ah I just mentioned the branch and meant to propose it. Actually the branch is at least 4 seqs, and one more in Sierra Leone (EPI_ISL_19421077). Another LF.7+S:A475V seq in MD, US is EPI_19420046 without T20799C.

They shall be independent branches given many seqs get only T20799C.

**Comment by aviczhl2** [comment]
+1 Australia

**Comment by FedeGueli** [comment]
3 continents for this

**Comment by FedeGueli** [comment]
+1 Scotland

there is now a second LF.7 branch w 475V  coming from Nigeria this time:
<img width="1167" alt="Screenshot 2024-10-02 alle 11 30 17" src="https://github.com/user-attachments/assets/20e9287f-a549-4dfb-ace6-063567ebc831">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice13_genome_test_7b41_d11a40.json?label=id:node_11680428
Query: C22986T,-T20799C,C8818T, A22893G,-C6310T 
that catches one sample fromSpain likely recombinant of this with Kp.3.1.1

**Comment by Sinickle** [comment]
Together, these two lineages are looking quite fast so far.

**Comment by FedeGueli** [comment]
7 England

**Comment by xz-keg** [comment]
+1 GBW from Turkey

**Comment by Sinickle** [comment]
8 seqs from Qatar today that fit into the branch with C6310T. This is a part of Qatar's first upload in the last half year, which contained 24 seqs, all collected in September.

**Comment by FedeGueli** [comment]
> +1 Scotland
> 
> there is now a second LF.7 branch w 475V coming from Nigeria this time 

and this went to 5 from Sweden today better proposing it

**Comment by FedeGueli** [comment]
> T20799C,C22986T

not got by the query i will re look at everything

**Comment by FedeGueli** [comment]
> > T20799C,C22986T
> 
> not got by the query i will re look at everything

Ok now the tree looks like this with 4 LF.7 sublinegaes with S:A475V:
<img width="1166" alt="Screenshot 2024-10-09 alle 20 36 29" src="https://github.com/user-attachments/assets/bac04a62-7c77-448f-b1bf-2ca4b8d671e0">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_2ba18_6cc7e0.json?branchLabel=nuc%20mutations&f_userOrOld=uploaded%20sample&label=id:node_7352632

@xz-keg what about to change this issue in a multiple lineages issue for LF.7+ 475V ??

**Comment by xz-keg** [comment]
> @xz-keg what about to change this issue in a multiple lineages issue for LF.7+ 475V ??
> 

changed.

**Comment by FedeGueli** [comment]
thx

**Comment by Sinickle** [comment]
Qatar uploaded 11 more sequences today, 6 of which are the Qatar branch in this issue. So, 14/35 total from Qatar.

**Comment by FedeGueli** [comment]
Br.1 +2 Scotland

**Comment by xz-keg** [comment]
Br.1 +1 GBW from Nigeria

**Comment by FedeGueli** [comment]
ping @corneliusroemer eyes on this

**Comment by xz-keg** [comment]
Branch 2: +8 Qatar, 25 now.

**Comment by FedeGueli** [comment]
> Branch 2: +8 Qatar, 25 now.

Please propose it

**Comment by DailyCovidCases** [comment]
Please propose branch 1 and 3 when it reaches 20 seqs

**Comment by xz-keg** [comment]
branch 1 designated LF.7.2.1

**Comment by xz-keg** [comment]
B2 is proposed and B3 seems stale, I'm closing this.

**Comment by FedeGueli** [comment]
> LF.7 > C17436T > Orf1a:P2046L (C6402T) > S:A475V (C22986T)
> Query: C17436T,C6402T,C22986T
> Samples: 2
> Country: Sweden

this one you didnt include in the branches is now 2

**Comment by FedeGueli** [comment]
> C17436T,C6402T,C22986T

now this is 4 >> adding it as a branch 4 with seqs also from Hong Kong and Texas

In the meanwhile Br.3 goes to 5 with Ireland

reopening the issue

**Comment by FedeGueli** [comment]
Branch 2 designated LF.7.1.2 via https://github.com/cov-lineages/pango-designation/commit/528407de862b007b0a427b0926f9afa3237a86e1

**Comment by FedeGueli** [comment]
Branch 4 up to 5 England

**Comment by xz-keg** [comment]
Branch 4: +3 Qatar

**Comment by FedeGueli** [comment]
Br.3 +1 Denmark new place.

**Comment by FedeGueli** [comment]
Br.3 +1 Ghana (GBW)

**Comment by xz-keg** [comment]
B4 +1 NY

**Comment by FedeGueli** [comment]
> B4 +1 NY

also Br.3 went to 8 England

**Comment by xz-keg** [comment]
one more LF.7+S:A475V from Qatar but a singlet and do not belong to any of the above branches. 

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_1a2f1_d4f3b0.json?gt=nuc.29119T&label=id:node_5671859

![image](https://github.com/user-attachments/assets/c0b08e8c-5c9b-48d5-891a-1748bf7f4e3f)

**Comment by FedeGueli** [comment]
> one more LF.7+S:A475V from Qatar but a singlet and do not belong to any of the above branches.
> 
 
Noticed that one too. Query for it: C4890T, C11565T, G25012A

**Comment by FedeGueli** [comment]
10 for Br.4 England

**Comment by FedeGueli** [comment]
Singlet from Italy with S:A475S:
LF.7>> A15828G > C18441T > ORF1b:P255S (C14230T),S:A475S (G22985T), ORF7a:T28I (C27476T)
Query: A15828G, C18441T ,G22985T

If it grows i will add it as a branch

**Comment by FedeGueli** [comment]
Br.4 went to 14 France, Uk

**Comment by FedeGueli** [comment]
Br.4 went to 15 Israel cc @corneliusroemer

**Comment by FedeGueli** [comment]
BR.4 >> 18 +3 England

**Comment by FedeGueli** [comment]
BR.4 > 19 Germany

**Comment by xz-keg** [comment]
> BR.4 > 19 Germany

It is 23 now, also in Denmark and Spain. Propose it?

**Comment by FedeGueli** [comment]
> > BR.4 > 19 Germany
> 
> It is 23 now, also in Denmark and Spain. Propose it?

Now Proposed in https://github.com/cov-lineages/pango-designation/issues/2836

**Comment by FedeGueli** [comment]
i think we can close this one i will track Br.3 prvtly

**Comment by FedeGueli** [comment]
Br.4 designated LF.7.3.1 via https://github.com/cov-lineages/pango-designation/commit/17508bfb81b7eb0ce399f8e4d3a3bddb9c31c93a#diff-ead4244ff49c81bc758e9f068f5ef42156bd985b9c86de8fa4d6fcd7f2829090R1297

**Comment by FedeGueli** [comment]
Singlet LF.7.3.1 + 475V from Netherlands added as branch 6
<img width="1174" alt="Screenshot 2024-12-11 alle 10 32 16" src="https://github.com/user-attachments/assets/a742cde0-132c-40a2-b607-1b5d62cb40d1">

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_43629_95ae00.json?c=userOrOld&label=id:node_7222242

**Comment by FedeGueli** [comment]
Br.3 went to 15 with two GBW from Oman reopening it

**Comment by HynnSpylor** [comment]
Proposal for a new LF.7.2.1 sub-branch: LF.7.2.1>ORF1a:S539L (C1878T)>C11373T, T21973A (S:N137K)
8 seqs now (Denmark 2, Sweden 2, France 2, Netherlands 1, Tanzania 1 (detected from US International Airport)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_235a8f_fc1580.json

![联想截图_20241216140232](https://github.com/user-attachments/assets/47449f92-e0ff-4d55-b44c-4cc3c44c4b65)

**Comment by xz-keg** [comment]
> Proposal for a new LF.7.2.1 sub-branch: LF.7.2.1>ORF1a:S539L (C1878T)>C11373T, T21973A (S:N137K) 8 seqs now (Denmark 2, Sweden 2, France 2, Netherlands 1, Tanzania 1 (detected from US International Airport)
> 
> https://nextstrain.org/fetch/genome.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_235a8f_fc1580.json
> 
> ![联想截图_20241216140232](https://private-user-images.githubusercontent.com/121703496/395978182-47449f92-e0ff-4d55-b44c-4cc3c44c4b65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzAwNTEsIm5iZiI6MTczNDMyOTc1MSwicGF0aCI6Ii8xMjE3MDM0OTYvMzk1OTc4MTgyLTQ3NDQ5ZjkyLWUwZmYtNGQ1NS1iNDRjLTRjYzNjNDRjNGI2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwNjE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjdjY2YxMjRmNmMxNjRjYjI5MWYyYzhlMDg5NThlZWFmMWJjMjc5ODA2ZTBmZDA4N2YxYjE3OWVlMWUyOTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qCcOjgEKxrDFKdMRSztrhIY-Ruh8-Q_qzlW_kmKsmbU)

make a separate proposal pls

**Comment by FedeGueli** [comment]
LF.7.2.1 is splitted in two branches by some 475V dropout sequences from Sweden cc @angiehinrichs:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_test_f596_1aa100.json?label=id:node_7224291
<img width="1127" alt="Screenshot 2024-12-17 alle 17 50 08" src="https://github.com/user-attachments/assets/9620eb15-ba61-4cb1-895b-5f75b59d3e8b" />

**Comment by AngieHinrichs** [comment]
> LF.7.2.1 is splitted in two branches by some 475V dropout sequences from Sweden cc @AngieHinrichs

Thanks!  It should be fixed in tomorrow's build (2024-12-19).

**Comment by FedeGueli** [comment]
> > LF.7.2.1 is splitted in two branches by some 475V dropout sequences from Sweden cc @AngieHinrichs
> 
> Thanks! It should be fixed in tomorrow's build (2024-12-19).

Thank you Angie!

**Comment by FedeGueli** [comment]
Br.3 up to 18

**Comment by FedeGueli** [comment]
Br.3 19

**Comment by xz-keg** [comment]
> Br.3 19

I'll propose it.

**Comment by FedeGueli** [comment]
> > Br.3 19
> 
> I'll propose it?

thx please

**Comment by xz-keg** [comment]
> > > Br.3 19
> > 
> > 
> > I'll propose it?
> 
> thx please

add a lot of new -s,  correct toll shall be 13.

**Comment by Over-There-Is** [comment]
Another LF.7.1.3+S:A475V? Russia and Japan

**Comment by FedeGueli** [comment]
> Another LF.7.1.3+S:A475V? Russia and Japan

added 4 more branches thx

**Comment by FedeGueli** [comment]
Br.6 +1 old

**Comment by FedeGueli** [comment]
Br.3 new query . T3565C,C8818T, T16600C,C22986T,-16017,-A4838G,-C2003T,-25624,-A1124G,-G8017T,-C17436T,-T20799C,-C6310T,-T847C,-C24444T,-C7688T,-C7051T,-G4504A finds only 18

**Comment by xz-keg** [comment]
add branch 11, another LF.7.1+S:A475V

**Comment by FedeGueli** [comment]
Br.3 query adjusted: T3565C,C8818T, T16600C,C22986T,-16017,-A4838G,-C2003T,-25624,-A1124G,-G8017T,-C17436T,-T20799C,-C6310T,-T847C,-C24444T,-C7688T,-C7051T,-G4504A,-G27415A,-C26607T,-G3939T

**Comment by FedeGueli** [comment]
Almost every branch are dead , i m tempted closing this , waht do u think @xz-keg ?

**Comment by FedeGueli** [comment]
branch 8 went to 14 all from Russia. @Over-There-Is please propose it.

**Comment by FedeGueli** [comment]
Br.9 and 11 revived (likely slow) added branch 14 LF.7.1.3+704L+475V from Russia reopening

**Comment by xz-keg** [comment]
B3 is actually parent of LF.7.9. I think the issue can be closed for now.

**Comment by FedeGueli** [comment]
> B3 is actually parent of LF.7.9. I think the issue can be closed for now.

agree there is only br.14 that being recent maybe will be detected further even if sampling in Russia is very scattered and always uploaded with delay.

**Comment by FedeGueli** [comment]
Added LF.7.7.2 +475V branch a canadian cluster as Br.15 
and LF.7.7.1 + 475V a South American internationally spread branch worth to track, hence i reopend the issue

**Comment by xz-keg** [comment]
> Added LF.7.7.2 +475V branch a canadian cluster as Br.15 and as branch 16 i have added LF.7.7.1 + 475V [a South American internationally spread branch](https://nextstrain.org/fetch/genome.ucsc.edu/trash/hgPhyloPlace/subtreeAuspice1_genome_be6ee_e0e800.json?label=id:node_7156432) worth to track, hence i ve reopened the issue

please propose in separate issues. Tasklist is to be closed.

**Comment by FedeGueli** [comment]
Br.15  G1274T,C22986T,G3939T goes 13 still a cluster

**Comment by Walde1nsamkeit** [comment]
cov-lineages/pango-designation#2944 branch 2

**Comment by FedeGueli** [comment]
> [cov-lineages/pango-designation#2944](https://github.com/cov-lineages/pango-designation/issues/2944) branch 2

it is not that one is LF.7.1.2

**Comment by xz-keg** [comment]
branch 14: +3 Kazak
