### ISSUE TITLE
Multiple XBB.1.22.1 lineages with S:R408X

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#410]
<a name="task_header"></a>
```[tasklist]
### Multiple `XBB.1.22.1` lineages with `S:R408N` or `S:R408G`
- [ ] [Branch 1](#branch_1): ~~**FY.1.1** > G22785A(**S:R408N**) [Query: `G18811A, G21809T, G22785A`, 24 seqs, 09/18]~~ Slow.
- [ ] [Branch 2](#branch_2): ~~**XBB.1.22.1** > C925A(ORF1a:D220E), G2265A(ORF1a:C667Y), C23585A(**S:Q675K**) > G22785A(**S:R408N**) [Query: `G2265A, G22785A, C23585A`, 15 seqs , 09/21]~~, a sub-branch of cov-lineages/pango-designation#2053 proposed by @HynnSpylor , Slowly grows in SEA region.
- [ ] [Branch 3](#branch_3): ~~**XBB.1.22.1** > C925A(ORF1a:D220E), G2265A(ORF1a:C667Y), C23585A(**S:Q675K**) > A8072G(ORF1a:N2603D), C13115T, C18744T, A22784G(**S:R408G**) [Query: `A22784G, G25423A, C27427A`, 20 seqs, 09/16]~~ Slowly grows in NA region.
- [ ] [Branch 4](#branch_4): ~~**FY.5** > A6019G > G28300A(**ORF9b:S6N**) > C22088T(**S:L176F**) > C10408T, A22784G(**S:R408G**) [Query: `A6019G, C22088T, A22784G`, 4 seqs , 08/30]~~ Inactive
- [ ] [Branch 5](#branch_5): **XBB.1.22.1** > G2246A(ORF1a:G661S), G26888A > G25019T(**S:D1153Y**) > C23709T(**S:T716I**), C24023T > T13890C, G22785A(**S:R408N)**, A28168G(ORF8:E92G) [Query: `G2246A, G22785A, G25019T`, 4 seqs, 09/05]
- [ ] [Branch 6](#branch_6): **FY.3** > C23191T > T10810C > T1216C, G22785A(**S:R408N**) [Query: `T10810C, G22785A, C23191T`, 4, 09/14]
- [ ] #296 , proposed by @FedeGueli , Phylogenetic order follows: **FY.6** > C13620T > A23989C > G22785A(**S:R408N**) [Query: `C13620T, G22785A, A23989C`, 36, 09/20]
```

<a name="branch_1"></a>
### Branch 1: `FY.1.1` with `S:R408N`

<details><summary>Slow</summary>

**Defining Mutations:** FY.1.1 > G22785A(S:R408N over existing R408S/A22786C)
**Query:** G22785A, G21809T, G18811A
**Earliest seq:** 2023-03-15 (EPI_ISL_17487887, Zhejiang, China)
**Latest seq:** 2023-06-12 (EPI_ISL_17815912, Singapore)
**Sampled Countries:** Malaysia (8), China (5, Guangdong/3, Yunnan/1, Zhejiang/1), Singapore (3), Australia (2), South Korea (2), Thailand (1)

<details><summary>Genomes: </summary>
EPI_ISL_17388568, EPI_ISL_17487887, EPI_ISL_17502933, EPI_ISL_17502951, EPI_ISL_17563694, EPI_ISL_17604181, EPI_ISL_17640397, EPI_ISL_17671127, EPI_ISL_17691828, EPI_ISL_17698150, EPI_ISL_17698227, EPI_ISL_17698239, EPI_ISL_17698981, EPI_ISL_17709531, EPI_ISL_17715941, EPI_ISL_17778659, EPI_ISL_17790422, EPI_ISL_17807880, EPI_ISL_17815912, EPI_ISL_17823700-17823701
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice3_genome_2653e_c639b0.json?c=gt-S_408&label=id:node_6907676
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/471c00b4-ff01-4b57-ac27-eea091232084)

</details>

[Back to Tasklist](#task_header)

---

<a name="branch_2"></a>
### Branch 2: `XBB.1.22.1` with `S:Q675K` mini-saltation then `S:R408N`, sub-lineage of cov-lineages/pango-designation#2053

<details><summary>Slowly grows in SEA region</summary>

**Defining Mutations:** XBB.1.22.1 > C925A(ORF1a:D220E), G2265A(ORF1a:C667Y), C23585A(S:Q675K) > G22785A(S:R408N over existing R408S/A22786C)
**Query:** G2265A, C23585A, G22785A
**Earliest seq:** 2023-03-28 (EPI_ISL_17503882, Brunei)
**Latest seq:** 2023-06-19 (EPI_ISL_17837743, Singapore)
**Sampled Countries:** Malaysia (4), Brunei (2), Belgium (1), China (1, Shanghai), Singapore (1)

<details><summary>Genomes: </summary>
EPI_ISL_17503882, EPI_ISL_17503885, EPI_ISL_17712546, EPI_ISL_17786621, EPI_ISL_17836615, EPI_ISL_17837743, EPI_ISL_17859155, EPI_ISL_17884247, EPI_ISL_17950413,
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2653e_c639b0.json?label=id:node_6909142
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/f96772c1-7b32-416d-a1b7-5ae524f0c640)

</details>

[Back to Tasklist](#task_header)

---

<a name="branch_3"></a>
### Branch 3, `XBB.1.22.1` 2-step mini-saltation with `S:Q675K` then `S:R408G`, another sub-lineage of cov-lineages/pango-designation#2053

<details><summary>Slowly grows in NA region</summary>

**Defining Mutations:** XBB.1.22.1 > C925A(ORF1a:D220E), G2265A(ORF1a:C667Y), C23585A(S:Q675K) > A8072G(ORF1a:N2603D), C13115T, C18744T, A22784G(S:R408G over existing R408S/A22786C), G25423A(ORF3a:G11R), C27427A(ORF7a:L12I)
**Query:** A22784G, G25423A, C27427A
**Earliest seq:** 2023-06-06 (EPI_ISL_17951461, Hawaii)
**Latest seq:** 2023-06-23 (EPI_ISL_17979140, California)
**Sampled Countries:** USA (5, Arizona/2, California/1, Hawaii/1, Tennessee/1)

<details><summary>Genomes: </summary>
EPI_ISL_17856656, EPI_ISL_17951461, EPI_ISL_17976413, EPI_ISL_17976435, EPI_ISL_17979140
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2653e_c639b0.json?label=id:node_6909186
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/80ea9cdd-2caf-4633-8231-2183a0794f45)

</details>

[Back to Tasklist](#task_header)

---

<a name="branch_4"></a>
### Branch 4: `FY.5` with `S:R408G`

<details><summary>Inactive</summary>

**Defining Mutations:** FY.5 > A6019G > G28300A(**ORF9b:S6N**) > C22088T(**S:L176F**) > C10408T, A22784G(**S:R408G**)
**Query:** `A6019G, C22088T, A22784G`
**Earliest seq:** 2023-05-30 (`EPI_ISL_17835856`, Jakarta, Indonesia)
**Latest seq:** 2023-08-15 (`EPI_ISL_18161750`, Iowa, USA)
**Sampled Countries:** South Korea (2), USA (1), Indonesia (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17835856, EPI_ISL_18031163, EPI_ISL_18046949, EPI_ISL_18161750`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice4_genome_2653e_c639c0.json?c=gt-S_408&gmax=25384&gmin=21563
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/d213ab2b-7320-48c5-9d0a-72e8e10a432d)

</details>

[Back to Tasklist](#task_header)

---

<a name="branch_5"></a>
### Branch 5: `XBB.1.22.1` with `S:R408N`, `S:T716I`, `S:D1153Y`

**Defining Mutations:** XBB.1.22.1 > G2246A(ORF1a:G661S), G26888A > G25019T(**S:D1153Y**) > C23709T(**S:T716I**), C24023T > T13890C, G22785A(**S:R408N**), A28168G(ORF8:E92G)
**Query:** `G2246A, G22785A, G25019T`
**Earliest seq:** 2023-06-29 (`EPI_ISL_18076051`, Colmar, France)
**Latest seq:** 2023-08-20 (`EPI_ISL_18221560`, Mulhouse, France)
**Sampled Countries:** France (2), Lebanon (1), USA (1)

<details><summary>Genomes: </summary>

`EPI_ISL_18012789, EPI_ISL_18076051, EPI_ISL_18216522, EPI_ISL_18221560`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice5_genome_2653e_c639c0.json?c=gt-S_408&gmax=25384&gmin=21563&label=id:node_6915951
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/4163bdb7-0636-41b5-8739-c17cdb0a823e)

[Back to Tasklist](#task_header)

---

<a name="branch_6"></a>
### Branch 6: `FY.3` with `S:R408N`

**Defining Mutations:** `FY.3` > `C23191T` > `T10810C` > `T1216C, G22785A(S:R408N)`
**Query:** `T10810C, G22785A, C23191T`
**Earliest seq:** 2023-07-26 (`EPI_ISL_18096933`, Nagasaki, Japan)
**Latest seq:** 2023-08-23 (`EPI_ISL_18257739`, Hiroshima, Japan)
**Sampled Countries:** Japan (4)

<details><summary>Genomes: </summary>

`EPI_ISL_18096933, EPI_ISL_18139672, EPI_ISL_18165254, EPI_ISL_18257739`</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice6_genome_2653e_c639c0.json?f_userOrOld=uploaded%20sample&label=id:node_6913141
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/408ea5dc-5da6-4859-8a5a-1dc8a213c6ab)

[Back to Tasklist](#task_header)

---

**Trivia:**

- `S:R408S/A22786C` introduced by **BA.2** now seems to have many alterations all of a sudden, especially on **XBB.1.22*** backbone. Instead of `S:R408G` and `S:R408N`, there's also a singlet with triple nuc mutations like `S:R408D(A22784G, G22785A, A22786C)`, `Spain/AN-PMC-35778/2023|EPI_ISL_17948484|2023-05-27`
![triple](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/5c7ddb9a-ef29-46f6-a234-757330fe22c5)

**Comment by FedeGueli** [comment]
Thx for keeping track of these ones, i have noticed this 408 thing on xbb.1.22.1 backbone in the issue you.mentioned: https://github.com/cov-lineages/pango-designation/issues/2053#issuecomment-1615976530

**Comment by FedeGueli** [comment]
@NkRMnZr thanks for tracking them. they seem to me all slow. Closing them all now.

**Comment by FedeGueli** [comment]
> Made an update, was courious which one surges after a long hiatus, and it was #296 @FedeGueli

Thank you. I ve reopened it

**Comment by FedeGueli** [comment]
Thx for tracking them
