### ISSUE TITLE
Multiple FL.2.3 lineages with S:F456L (Branch 1 with further S:L455F)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#526]
<a name="task_header"></a>
```[tasklist]
### Multiple FL.2.3 lineages with S:F456L
- [ ] [Branch 1](#branch_1): **FL.2.3 (with G28839T/N:R189L)** > `T22928C(S:F456L)` [Query: `A17615G, T22928C, G28839T`, 37 seqs, 11/17]
- [ ] [Branch 2](#branch_2): ~~**FL.2.3** > `G28839T(N:R189L)` > `T16977C` > `T22928C(S:F456L)` [Query: `T16977C, A17615G, T22928C`, 5 seqs, 08/07]~~ _Inactive_
- [ ] Branch 1 got further `S:L455F`, follows: **Branch 1 (G28839T/N:R189L)** > `G22927T(S:L455F), T27288C` [Query: `T4579A, A17615G, G22927T`, 9 seqs, 11/17] now tracked by @Over-There-Is from #1068 with further `S:Q14R` branch
- [ ] Singlets, Doublets and [Triplets](#triplets). Query for all **FL.2.3** with `S:F456L`: `spike_F456, T4579A, A17615G`, 53 seqs, as of 11/22. [Checking updates](https://github.com/sars-cov-2-variants/lineage-proposals/issues/526#issuecomment-1671097691), with credit to @Over-There-Is
```

<a name="branch_1"></a>
### Branch 1

**Defining Mutations:** `FL.2.3` > `T22928C(S:F456L)`
**Query:** `C11956T, A17615G, T22928C, -G4881A, -T16977C, -C23123T`
**Earliest seq:** 2023-06-05 (`EPI_ISL_17831356`, Pannes, France)
**Latest seq:** 2023-07-20 (`EPI_ISL_18055248`, Ontario, Canada )
**Sampled Countries:** China (4, Guangdong), Canada (2, Ontario), France (1), USA (1)

<details><summary>Genomes: </summary>

`EPI_ISL_17831356, EPI_ISL_18022536, EPI_ISL_18034758, EPI_ISL_18034800, EPI_ISL_18036427, EPI_ISL_18036680, EPI_ISL_18055248, EPI_ISL_18055262`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28f0a_b938b0.json?label=id:node_7021952
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ba9f1b85-f19b-4467-b7a4-5d86d9483552)

[Back to Tasklist](#task_header)

---

<a name="branch_2"></a>
### Branch 2

<details><summary>Inactive</summary>

**Defining Mutations:** FL.2.3 > G28839T(**N:R189L**) > T16977C > T22928C(**S:F456L**)
**Query:** `T16977C, A17615G, T22928C`
**Earliest seq:** 2023-05-01 (EPI_ISL_17625561, Shanghai, China)
**Latest seq:** 2023-06-05 (EPI_ISL_17836662, Shanghai, China)
**Sampled Countries:** China (4, Shanghai)

<details><summary>Genomes: </summary>

`EPI_ISL_17625561, EPI_ISL_17811306, EPI_ISL_17811318, EPI_ISL_17836662`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_28f0a_b938b0.json?f_userOrOld=uploaded%20sample&label=id:node_7022200
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/6e4ea94b-4bd6-46e9-b0a3-eab9bfca6f35)

</details>

[Back to Tasklist](#task_header)

**UShER:**

**Trivia:**
- Note that the only sample from Branch 1 without `N:R189L` is `France/GES-IPP15690/2023|EPI_ISL_17831356|2023-06-05`, so these may be the same branch got separated by potential dropout.
- `Guangdong/GDCDC_SZHG_1719/2023|EPI_ISL_18036297|2023-06-03` seems to be a recominant of Branch 1 with XBB.2.3*, the query is using `-C23123T` to filter it out.

---

<a name="triplets"></a>
### Triplets

- `South_Korea/KDCA261207/2023|EPI_ISL_18239231|2023-08-15` and `South_Korea/KDCA261464/2023|EPI_ISL_18239448|2023-08-18`
**FL.2.3** > `G4881A(ORF1a:S1539N)` > `T7633C, C12754T, C17403T, T22928C(S:F456L), C26936T, C28087T(ORF8:A65V)` [Query: `G4881A, A17615G, T22928C`, 3, 09/27]

[Back to Tasklist](#task_header)

**Comment by Over-There-Is** [comment]
> Guangdong/GDCDC_SZHG_1719/2023|EPI_ISL_18036297|2023-06-03 FL.2.3 / XBB.2.3.7 Mutations based on FL.2.3: A4479C, T9076C, C12853T | T22317Grev, A22320G, T22928C, C23123T, C26447T, C27431T, T27915Grev, C28297Trev, C28717A, G29706T Mutations based on XBB.2.3: T4234Crev, A4479C, T4579A, G5720A, A6536Grev, T9076C, C11956T, C12789T, C12853T, T16342C, A17615G | T22928C, C26447T, C28717A
> 
> Breakpoint: **17615~22317**
> 
> FL.2.3+T9076C 5 seqs (All in Nanping, Fujian, China) FL.2.3> G28980T(N:G236V)> **T9076C**, T28157G(~Orf8:I88M~)
> 
> XBB.2.3+C26447T, C28717A 14seqs (Fujian 12[Nanping 10, Sanming 2], Singapore 1, Victoria, Australia 1) XBB.2.3.7> G11042A(Orf1a:V3593I)> G1401A(Orf1a:G379E)> A3503G(Orf1a:N1080D), C8950T> **C28717A**> **C26447T(E:S68F)**
> 
> Private mutations: **A4479C(Orf1a:K1405T), C12853T, T22928C(S:F456L)**
> 
> Probably originates in Nanping, and exported to somewhere out of Chinese Mainland, and detected by Shenzhen Customs when entering.

#108

**Comment by Over-There-Is** [comment]
I think the French sequences is just convergent, and the branch 1 should be FL.2.3> N:R189L> S:F456L.
But I am not sure whether the branch 2 is FL.2.3> N:R189L> S:F456L> T16977C or FL.2.3> N:R189L> T16977C> S:F456L.
FL.2.3> N:R189L> T16977C have only 1 sequence in Canada, but a synonymous mutation should be less convergent than S:F456L.

**Comment by FedeGueli** [comment]
One more sequence fro Brnach 2 collected in July in Shanghai

**Comment by Over-There-Is** [comment]
Branch 1 +1(Shanghai)
and a sequence from Henan under T14961C branch gains F456L convergently.

**Comment by FedeGueli** [comment]
why i got 10 with T4579A, A17615G, T22928C, -T16977C, -C23123T??

**Comment by FedeGueli** [comment]
Thank you!

**Comment by Over-There-Is** [comment]
But I don't think EPI_ISL_18105470 belongs to Branch 1.

**Comment by FedeGueli** [comment]
I want to see how they will behave with the newcoming dominant lineages.

**Comment by Over-There-Is** [comment]
NY+1

**Comment by Over-There-Is** [comment]
USA\/WA-GBW-H10-016-4168\/2023|EPI_ISL_18239091|2023-08-31 FL.2.3>N:R189L>S:F456L>Saltated and gained L455F.

**Comment by Over-There-Is** [comment]
2 South Korean sequences under FL.2.3> G4881A(Orf1a:S1539N) gained F456L.

**Comment by Over-There-Is** [comment]
![2023-09-09 (9)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/5eb8654e-be3a-40d2-a3b1-15f53592ab59)
![2023-09-09 (10)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/1e0dca1e-0fab-47aa-bf25-6712f49abe05)
![2023-09-09 (11)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/b5b54738-5349-4764-9eef-74268f646969)
![2023-09-09 (5)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/ec13716e-e2fd-4b46-991b-7c2bcb0f286f)
![2023-09-09 (6)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/77bddea9-09da-40ac-b0b2-bf953060d8ae)

**Comment by Over-There-Is** [comment]
Since F456L is homoplastic enough, and N:R189L is the largest branch of FL.2.3, EPI_ISL_17831356 and N:R189L>S:F456L are doubtless unrelated. But I'm not sure whether Canada/NS-NSH-632615/2023|EPI_ISL_17799177|2023-06-05 a sequence with S:F456L dropout, and whether branch 2 a subbranch of N:R189L>S:F456L.

**Comment by FedeGueli** [comment]
We could add them as branches if you agee just give me the queries and the defining mutations for each branch.

**Comment by Over-There-Is** [comment]
Branch A: G28839T, T22928C, -T16977C
15 seq, CA 6, CN 5, US 4. 06-10~08-31.
Still growing, 1 sequence gained L455F recently.
FL.2.3> G28839T(N:R189L)> T22928C(S:F456L)

Branch B: G28839T, T22928C, T16977C
5 seq, Shanghai, China. 05-01~07-05.
FL.2.3> G28839T(N:R189L)> T16977C> T22928C(S:F456L) or FL.2.3> G28839T(N:R189L)> T22928C(S:F456L)> T16977C?

Branch C: A17615G, G4881A, T22928C
2 seq, South Korea, new branch.
FL.2.3> G4881A(Orf1a:S1539N)> T7633C, C12754T, C17403T, T22928C(S:F456L), C26936T, C28087T(~Orf8:A65V~)

Singlet a: Guangdong/GDCDC_SZHG_1719/2023|EPI_ISL_18036297|2023-06-03 inactive
T9076C, C28717A
FL.2.3> *G28980T(N:G236V)*> **T9076C**, *T28157G(~Orf8:I88M~)* recombined with
XBB.2.3.7> *G11042A(Orf1a:V3593I)*> *G1401A(Orf1a:G379E)*> *A3503G(Orf1a:N1080D)*, *C8950T*> **C28717A**> **C26447T(E:S68F)**
then A4479C(Orf1a:K1405T), C12853T, T22928C(S:F456L)

Singlet b: Henan/PYCDC-LG23695/2023|EPI_ISL_18105470|2023-07-18 inactive
A17615G, T14961C, T22928C
FL.2.3> T14961C> C2704T, C22388T, T22928C(S:F456L), A25201C

Singlet c: France/GES-IPP15690/2023|EPI_ISL_17831356|2023-06-05 inactive
G5720A, A17615G, T22928C, -G28839T, -G4881A, -A22320G, -T14961C
FL.2.3> G3197A(Orf1a:D978N), C4890A(Orf1a:T1542N), T22928C(S:F456L), C27247A(Orf6:L16I)

**Comment by FedeGueli** [comment]
> > @FedeGueli
> > We could add them as branches if you agee just give me the queries and the defining mutations for each branch.
> 
> Now things got complicated, as it is when `FL.2.3` designated (homoplastic and `spike_146-148` mutation-or-artifact involved). If `N:R189L` did happen before `S:F465L`, Branch 1 and 2 could be merged, and the French lineage will be decided whether it has dropout or not; if current path of `S:F456L` > `N:R189L` is correct, it would be the situation @Over-There-Is [listed above](https://github.com/sars-cov-2-variants/lineage-proposals/issues/526#issuecomment-1712438500) with multiple very similar lineages with `S:F456L`

@angiehinrichs what do you think?

**Comment by Over-There-Is** [comment]
`A405G, A17615G, G28839T` gives 651 sequences, and `A405G, -A17615G, G28839T` only gives 38, and 24 Indian low-quality sequences are included. That means, for XBB* variants, G28839T is not homoplastic. So, it is more likely for N:R189L to come before S:F456L.

**Comment by FedeGueli** [comment]
> `A405G, A17615G, G28839T` gives 651 sequences, and `A405G, -A17615G, G28839T` only gives 38, and 24 Indian low-quality sequences are included. That means, for XBB* variants, G28839T is not homoplastic. So, it is more likely for N:R189L to come before S:F456L.

That is what i recalled too. Thx.

**Comment by Over-There-Is** [comment]
FLip +1
![2023-09-15 (1)](https://github.com/sars-cov-2-variants/lineage-proposals/assets/38100637/098b612c-83b3-44fb-8e05-600d6e9b21c1)

**Comment by AngieHinrichs** [comment]
> So, it is more likely for N:R189L to come before S:F456L.

I think this is fixed in the 2023-09-15 tree which will be on the main site in about an hour.

**Comment by Over-There-Is** [comment]
New singlet: USA/KY-CDC-QDX84229412/2023|EPI_ISL_18265617|2023-08-21
FL.2.3> G28980T(N:G236V)> C7948T> C13366T> T22930G(S:F456L), T25496C(Orf3a:I35T), C27752T(Orf7a:T120I)
Rather than T22928C, this one is T22930G.

**Comment by Over-There-Is** [comment]
New singlet: Canada\/NS-NSH-644347\/2023|EPI_ISL_18282191|2023-09-01
FL.2.3> G28839T(N:R189L)> C19970T(Orf1b:A2168V)> C6636T(Orf1a:T2124I), G22927C(S:L455F), T22930A(S:F456L), A29499T(N:Q409L)

**Comment by Over-There-Is** [comment]
One more sequence from FL.2.3> G4881A(Orf1a:S1539N)> T7633C, C12754T, C17403T, T22928C(S:F456L), C26936T branch, without Orf8:A65V

**Comment by Over-There-Is** [comment]
USA/NY-CDC-QDX84402965/2023|EPI_ISL_18375139|2023-08-25

**Comment by Over-There-Is** [comment]
Canada/BC-BCCDC-661172/2023|EPI_ISL_18453145|2023-10-14 new singlet?

**Comment by Over-There-Is** [comment]
> Branch A: G28839T, T22928C, -T16977C 15 seq, CA 6, CN 5, US 4. 06-10~08-31. Still growing, 1 sequence gained L455F recently. FL.2.3> G28839T(N:R189L)> T22928C(S:F456L)
> 
> Branch B: G28839T, T22928C, T16977C 5 seq, Shanghai, China. 05-01~07-05. FL.2.3> G28839T(N:R189L)> T16977C> T22928C(S:F456L) or FL.2.3> G28839T(N:R189L)> T22928C(S:F456L)> T16977C?
> 
> Branch C: A17615G, G4881A, T22928C 2 seq, South Korea, new branch. FL.2.3> G4881A(Orf1a:S1539N)> T7633C, C12754T, C17403T, T22928C(S:F456L), C26936T, C28087T(~Orf8:A65V~)
> 
> Singlet a: Guangdong/GDCDC_SZHG_1719/2023|EPI_ISL_18036297|2023-06-03 inactive T9076C, C28717A FL.2.3> _G28980T(N:G236V)_> **T9076C**, _T28157G(~Orf8:I88M~)_ recombined with XBB.2.3.7> _G11042A(Orf1a:V3593I)_> _G1401A(Orf1a:G379E)_> _A3503G(Orf1a:N1080D)_, _C8950T_> **C28717A**> **C26447T(E:S68F)** then A4479C(Orf1a:K1405T), C12853T, T22928C(S:F456L)
> 
> Singlet b: Henan/PYCDC-LG23695/2023|EPI_ISL_18105470|2023-07-18 inactive A17615G, T14961C, T22928C FL.2.3> T14961C> C2704T, C22388T, T22928C(S:F456L), A25201C
> 
> Singlet c: France/GES-IPP15690/2023|EPI_ISL_17831356|2023-06-05 inactive G5720A, A17615G, T22928C, -G28839T, -G4881A, -A22320G, -T14961C FL.2.3> G3197A(Orf1a:D978N), C4890A(Orf1a:T1542N), T22928C(S:F456L), C27247A(Orf6:L16I)

Branch C +2

**Comment by Over-There-Is** [comment]
> Canada/BC-BCCDC-661172/2023|EPI_ISL_18453145|2023-10-14 new singlet?

+3

**Comment by FedeGueli** [comment]
generally it looks still much slower than Hk.3 : https://cov-spectrum.org/explore/World/AllSamples/Past3M/variants?nextcladePangoLineage=HK.3*&nucMutations1=4579A%2CA17615G%2CT22928C&analysisMode=CompareToBaseline&
