### ISSUE TITLE
DV.7.1 diversity

### ISSUE THREAD

**Issue by oobb45729** [sars-cov-2-variants/lineage-proposals#566]
```[tasklist]
### Tasks
- [ ] DV.7.1 > ORF1a:K3353R(A10323G) >150 seq. https://github.com/sars-cov-2-variants/lineage-proposals/issues/559 (Many Israeli sequences lack coverage at S:455-456) https://github.com/cov-lineages/pango-designation/issues/2261
- [x] DV.7.1.1: DV.7.1 > ORF1a:K3353R(A10323G) > S:K679R(A23598G) https://github.com/sars-cov-2-variants/lineage-proposals/issues/732
- [x] DV.7.1.2: DV.7.1 > ORF1a:A4162V(C12750T)+ORF10:M1V(A29558G) https://github.com/cov-lineages/pango-designation/issues/2258 https://github.com/sars-cov-2-variants/lineage-proposals/issues/697
- [ ] DV.7.1.2 > nuc:A24373G > ORF1a:S2246L(C7002T) > S:G485R (G23015C) https://github.com/sars-cov-2-variants/lineage-proposals/issues/760
- [ ] DV.7.1.2 > nuc:A24373G > Orf3a:D210E(C26022A) > Orf1a:L980S(T3204C) > S:K679R (A23598G) 6 seq. https://github.com/sars-cov-2-variants/lineage-proposals/issues/750
- [ ] DV.7.1 > N:T135A(A28676G) >100 seq. https://github.com/sars-cov-2-variants/lineage-proposals/issues/729 https://github.com/cov-lineages/pango-designation/issues/2238
- [ ] DV.7.1 > ORF6:L61F(C27382T) >20 seq.
- [ ] DV.7.1 > ORF6:L61F(C27382T) > nuc:G21724A+S:Q183K(C22109A)+nuc:T28007C+N:A217S(G28922T) https://github.com/sars-cov-2-variants/lineage-proposals/issues/765
- [ ] DV.7.1 > nuc:C10228T > nuc:C10615T+nuc:T20833C+S:K478R(A22995G)+N:H300L(A29172T) 4 seq. https://github.com/sars-cov-2-variants/lineage-proposals/issues/737
```

**Comment by oobb45729** [comment]
I don't update this anymore.

**Comment by FedeGueli** [comment]
Thank you for your work @oobb45729
