### ISSUE TITLE
Very Diverse Tree Indicating Collection of EG.5.1*+S:157L besides EG.5.1.6 and HK.3.1

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#786]
Parent: EG.5.1*( and sometimes its first descendents as EG.5.1.1* or else)

Gisaid Inquiry : **-C5835T,-G22927T,C22033A,G21718T,C22480T** (The latter two indicates EG.5.1*, C22033A for F157L, and the first two removes potential EG.5.1.6* and HK.3.1* as they are already designated).

Sequences:96-8-9-1=78 total (7 England, 5 France, 1 Italy, 2 Japan, 2 Netherland, 2 Portugal, 11 Scotland, 3-1=2 South Korea, 2 Spain, 29-8-9=12 US, the rest 30 in various Chinese Provinces, of which Shanghai and Yunnan looks important)
8+9+1 seqs are removed as they are either EG.5.1.6*, or Spike-Only sequences.
Earliest:  EPI_ISL_18036594 Guangdong, China 06-18
Latest: EPI_ISL_18239743 France, 08-28
Usher Tree:https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1d1df_e27e30.json?f_userOrOld=uploaded%20sample&label=id:node_3064067
Picture of it: 
<img width="1244" alt="Screenshot 2023-09-10 at 4 39 09 PM" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/f3a48f22-1448-4c2e-ad83-ae0a4e48f0fe">

Note: I revived discussion of S:F157L in XBB* when searching for potential BA.2.75/XBB recombinations (as S:F157L is sign of XBB), yet instead I see just how widespread and fast this mutation arises in general XBB* population. After some works of other spotters and me, we spot and designate several lineages, and I thought it was over.
And just today, I decided to check over my issues and see how much they grow. EG.5.1.6* was certainly beyond my expectation, yet I found a large crowd of EG.5.1*+S:157L. The most noticible one is certainly the "flip" one-HK.3.1*, but a lot of unclassified lineages seem to exist, and they are everywhere (across many major subdivisions of EG.5.1), as shown in the picture.
And a lot of those are pretty new, I made a comparison between it, EG.5.1*, and EG.5.1*+flip. It is almost as fast as Flip I guess.

<img width="982" alt="2294B91F-FCF2-488F-A83D-94ECE08BD320" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/5134c991-97b4-41ba-973f-10080e298352">

I will try my best to get this part described. But help would be appreciated.

Update: Quite large uploads have increased total number of sequences to 109-8-10=91 now.

```[tasklist]
### Tasks
- [ ] Branch 1:EG.5.1->G670T ( universal reversion,questionable) C12439T, C22033A 22seqs, 3 countries  
      Gisaid Inquiry: C12439T,-C5835T,-G22927T,C22033A,G21718T,C22480T
- [ ] https://github.com/sars-cov-2-variants/lineage-proposals/issues/774
```

```[tasklist]
### Tasks
- [ ] #774
- [ ] Branch 2: EG.5.1* derivative with G670T, C12439T, C22033A
```

**Comment by krosa1910** [comment]
Lineage 1: Defining Mutations: G670T (orf1a_R135Srev=nsp1_R135Srev), C12439T on top of EG.5.1*
I think this is weird because it is defined by a reversion and a silent mutation, but whatever it seemed the largest thing I could dig out from this pile. Also it appeared in four region/countries (depending on how to count England and Scotland), so a little higher credibility
Gisaid Inquiry: C22033A,G21718T,C12439T,-T670G
18 sequences
Earliest: EPI_ISL_18228064 Scotland 07-29
Latest: EPI_ISL_18239744 France 08-28
<img width="947" alt="9BB7FCDE-D36A-4787-83E9-CE7EE2BD3F86" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/131021067/d84328c7-f336-4e50-abd4-5c635b594f18">

Lineage 2: Defining Mutations: S:S98F,S: F157L and some more on top of EG.5.1*
I don't know why it only showed up 8 sequences on my side, seems more than that. This is covered by #774 So I would leave the job of tracking it to Ryan

**Comment by FedeGueli** [comment]
ping @corneliusroemer have you already looked in S:F157L homoplasic in EG.5.1 and EG.5.1.1?

**Comment by krosa1910** [comment]
I now believe this has sustained population and steady growth because it has been uploaded everyday for the last 8 weekdays (that is the last week+ this week). Would try to sort out everything recognizable >5 to be a "lineage" (smaller will be sin/dou/tri/quadlet)

**Comment by FedeGueli** [comment]
Hi @krosa1910 could you provide a query please?

**Comment by FedeGueli** [comment]
![Schermata 2023-10-13 alle 11 37 49](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/ce1c0ff2-87ed-46c0-915d-4e8c2d505207)
the EG.5.1.1 top branch in your  first tree now designated HK.19

**Comment by FedeGueli** [comment]
I am not sure if milestoning this one , cause the secific queries miss the ones analyzed by you. let me know.
